version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
    - "80:80"
    depends_on:
      - app
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: 
      context: .      
      dockerfile: ./docker/app/Dockerfile 
    command: bundle exec puma -C config/puma.rb
    environment:
      - RAILS_ENV=production
    entrypoint: [./docker/app/prod-test.sh]
    volumes:
      - .:/myapp
    expose:
      - "3000"
    depends_on:
      - db
